spring:
  profiles:
    active: local
  messages:
    basename: messages, errors
    fallback-to-system-locale: false
  output:
    ansi:
      enabled: always
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
  # H2 데이터베이스
  dataSource:
    url: jdbc:h2:tcp://localhost/~/project-200
    username: sa
    password:
# Logging
logging:
#  config: classpath:logback-spring.xml
  level:
    root: info