spring:
  output:
    ansi:
      enabled: always
  server:
    address: ${SERVER_ADDRESS}
    port: ${SERVER_PORT}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  dataSource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
# Logging
logging:
  config: classpath:logback-spring.xml
  level:
    root: info